2023-01-29 18:21:21,606 INFO server Auth successful
2023-01-29 18:21:21,610 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 157, in run_function_and_return_result
    output = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 107, in run_function
    exec(imports)
  File "<string>", line 1, in <module>
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 37, in <module>
    from tensorflow._api.v2.compat.v2 import distribute
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/__init__.py", line 182, in <module>
    from . import experimental
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/__init__.py", line 10, in <module>
    from . import rpc
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/rpc/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.experimental.rpc.rpc_ops import Client
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/experimental/__init__.py", line 22, in <module>
    from tensorflow.python.distribute.failure_handling import failure_handling
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/failure_handling.py", line 34, in <module>
    from tensorflow.python.distribute.failure_handling import gce_util
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/gce_util.py", line 20, in <module>
    import requests
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-01-29 18:21:21,611 INFO werkzeug 127.0.0.1 - - [29/Jan/2023 18:21:21] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-01-29 18:39:23,256 INFO server Auth successful
2023-01-29 18:39:23,260 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 157, in run_function_and_return_result
    try:
  File "/home/saurabh/code-energy-consumption/server/server.py", line 107, in run_function
    app.logger.info(f"Imports: {imports}")
  File "<string>", line 1, in <module>
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 37, in <module>
    from tensorflow._api.v2.compat.v2 import distribute
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/__init__.py", line 182, in <module>
    from . import experimental
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/__init__.py", line 10, in <module>
    from . import rpc
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/rpc/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.experimental.rpc.rpc_ops import Client
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/experimental/__init__.py", line 22, in <module>
    from tensorflow.python.distribute.failure_handling import failure_handling
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/failure_handling.py", line 34, in <module>
    from tensorflow.python.distribute.failure_handling import gce_util
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/gce_util.py", line 20, in <module>
    import requests
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-01-29 18:39:23,261 INFO werkzeug 127.0.0.1 - - [29/Jan/2023 18:39:23] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-01-29 18:40:41,896 INFO server Auth successful
2023-01-29 18:40:41,901 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 157, in run_function_and_return_result
    try:
  File "/home/saurabh/code-energy-consumption/server/server.py", line 107, in run_function
    app.logger.info("Imports:", imports)
  File "<string>", line 1, in <module>
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 37, in <module>
    from tensorflow._api.v2.compat.v2 import distribute
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/__init__.py", line 182, in <module>
    from . import experimental
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/__init__.py", line 10, in <module>
    from . import rpc
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/rpc/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.experimental.rpc.rpc_ops import Client
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/experimental/__init__.py", line 22, in <module>
    from tensorflow.python.distribute.failure_handling import failure_handling
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/failure_handling.py", line 34, in <module>
    from tensorflow.python.distribute.failure_handling import gce_util
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/gce_util.py", line 20, in <module>
    import requests
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-01-29 18:40:41,902 INFO werkzeug 127.0.0.1 - - [29/Jan/2023 18:40:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-01-29 18:42:56,268 INFO server Auth successful
2023-01-29 18:42:56,272 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 157, in run_function_and_return_result
    try:
  File "/home/saurabh/code-energy-consumption/server/server.py", line 107, in run_function
    app.logger.info("Imports value: %s", imports)
  File "<string>", line 1, in <module>
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 37, in <module>
    from tensorflow._api.v2.compat.v2 import distribute
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/__init__.py", line 182, in <module>
    from . import experimental
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/__init__.py", line 10, in <module>
    from . import rpc
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/rpc/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.experimental.rpc.rpc_ops import Client
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/experimental/__init__.py", line 22, in <module>
    from tensorflow.python.distribute.failure_handling import failure_handling
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/failure_handling.py", line 34, in <module>
    from tensorflow.python.distribute.failure_handling import gce_util
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/distribute/failure_handling/gce_util.py", line 20, in <module>
    import requests
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-01-29 18:42:56,273 INFO werkzeug 127.0.0.1 - - [29/Jan/2023 18:42:56] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-01-29 18:44:47,553 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://129.173.67.60:5000
2023-01-29 18:44:47,553 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-01-29 18:45:10,413 INFO server Auth successful
2023-01-29 18:45:10,413 INFO server Imports value: import tensorflow as tf
2023-01-29 18:45:11,209 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-01-29 18:45:11,371 DEBUG h5py._conv Creating converter from 7 to 5
2023-01-29 18:45:11,371 DEBUG h5py._conv Creating converter from 5 to 7
2023-01-29 18:45:11,371 DEBUG h5py._conv Creating converter from 7 to 5
2023-01-29 18:45:11,371 DEBUG h5py._conv Creating converter from 5 to 7
2023-01-29 18:45:12,041 INFO werkzeug 127.0.0.1 - - [29/Jan/2023 18:45:12] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-29 18:45:12,171 INFO server Auth successful
2023-01-29 18:45:12,171 INFO server Imports value: import tensorflow as tf
2023-01-29 18:45:12,174 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 171, in run_function_and_return_result
    data = pickle.dumps(output)
TypeError: cannot pickle '_thread.RLock' object
2023-01-29 18:45:12,175 INFO werkzeug 127.0.0.1 - - [29/Jan/2023 18:45:12] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-01-31 17:49:00,622 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-01-31 17:49:00,622 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-01-31 17:49:09,021 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-01-31 17:49:09,021 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-01-31 17:49:23,517 INFO server Auth successful
2023-01-31 17:49:23,579 INFO server Imports value: import numpy as np
2023-01-31 17:49:23,582 INFO server response-value: <Response 80161 bytes [200 OK]>
2023-01-31 17:49:23,582 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 17:49:23] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 17:49:24,274 INFO server Auth successful
2023-01-31 17:49:24,275 INFO server Imports value: import numpy as np
2023-01-31 17:49:24,279 INFO server response-value: <Response 161762 bytes [200 OK]>
2023-01-31 17:49:24,279 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 17:49:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 17:49:24,453 INFO server Auth successful
2023-01-31 17:49:26,136 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-01-31 17:49:26,281 DEBUG h5py._conv Creating converter from 7 to 5
2023-01-31 17:49:26,281 DEBUG h5py._conv Creating converter from 5 to 7
2023-01-31 17:49:26,281 DEBUG h5py._conv Creating converter from 7 to 5
2023-01-31 17:49:26,281 DEBUG h5py._conv Creating converter from 5 to 7
2023-01-31 17:49:27,307 INFO server Imports value: import tensorflow as tf
2023-01-31 17:49:27,321 INFO server response-value: <Response 249 bytes [200 OK]>
2023-01-31 17:49:27,322 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 17:49:27] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 17:49:27,503 INFO server Auth successful
2023-01-31 17:49:27,503 INFO server Imports value: import tensorflow as tf
2023-01-31 17:49:27,507 INFO server response-value: <Response 449 bytes [200 OK]>
2023-01-31 17:49:27,507 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 17:49:27] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 18:30:27,942 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-01-31 18:30:27,942 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-01-31 18:30:38,170 INFO server Auth successful
2023-01-31 18:30:38,231 INFO server Imports value: import numpy as np
2023-01-31 18:30:38,233 INFO server response-value: <Response 80161 bytes [200 OK]>
2023-01-31 18:30:38,233 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 18:30:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 18:30:38,925 INFO server Auth successful
2023-01-31 18:30:38,926 INFO server Imports value: import numpy as np
2023-01-31 18:30:38,928 INFO server response-value: <Response 161762 bytes [200 OK]>
2023-01-31 18:30:38,928 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 18:30:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 18:30:39,103 INFO server Auth successful
2023-01-31 18:30:40,786 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-01-31 18:30:40,931 DEBUG h5py._conv Creating converter from 7 to 5
2023-01-31 18:30:40,932 DEBUG h5py._conv Creating converter from 5 to 7
2023-01-31 18:30:40,932 DEBUG h5py._conv Creating converter from 7 to 5
2023-01-31 18:30:40,932 DEBUG h5py._conv Creating converter from 5 to 7
2023-01-31 18:30:42,014 INFO server Imports value: import tensorflow as tf
2023-01-31 18:30:42,029 INFO server response-value: <Response 249 bytes [200 OK]>
2023-01-31 18:30:42,030 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 18:30:42] "POST /api/run_experiment HTTP/1.1" 200 -
2023-01-31 18:30:42,215 INFO server Auth successful
2023-01-31 18:30:42,215 INFO server Imports value: import tensorflow as tf
2023-01-31 18:30:42,219 INFO server response-value: <Response 449 bytes [200 OK]>
2023-01-31 18:30:42,219 INFO werkzeug 127.0.0.1 - - [31/Jan/2023 18:30:42] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:26:33,260 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-02-01 09:26:33,260 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-01 09:27:24,495 INFO server Auth successful
2023-02-01 09:27:24,495 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:24,519 INFO server Auth successful
2023-02-01 09:27:24,519 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:24,542 INFO server Auth successful
2023-02-01 09:27:24,542 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:26,785 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-01 09:27:27,075 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 09:27:27,075 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 09:27:27,075 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 09:27:27,075 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 09:27:28,502 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:27:28,503 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:28] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:28,504 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:27:28,504 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:28] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:28,505 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:27:28,505 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:28] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:28,749 INFO server Auth successful
2023-02-01 09:27:28,750 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:28,807 INFO server Auth successful
2023-02-01 09:27:28,807 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:28,808 INFO server Auth successful
2023-02-01 09:27:28,898 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:28,901 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:27:28,901 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:28] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:28,902 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:27:28,903 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:28] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:28,903 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:27:28,904 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:28] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:29,010 INFO server Auth successful
2023-02-01 09:27:29,011 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:29,011 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:27:29,012 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:29,023 INFO server Auth successful
2023-02-01 09:27:29,023 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:29,024 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:27:29,024 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:27:29,032 INFO server Auth successful
2023-02-01 09:27:29,033 INFO server Imports value: import tensorflow as tf
2023-02-01 09:27:29,033 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:27:29,033 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:27:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,320 INFO server Auth successful
2023-02-01 09:29:18,320 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,320 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:29:18,320 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,344 INFO server Auth successful
2023-02-01 09:29:18,344 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,344 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:29:18,344 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,429 INFO server Auth successful
2023-02-01 09:29:18,429 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,430 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:29:18,430 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,492 INFO server Auth successful
2023-02-01 09:29:18,492 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,493 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:29:18,493 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,500 INFO server Auth successful
2023-02-01 09:29:18,500 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,501 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:29:18,501 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,582 INFO server Auth successful
2023-02-01 09:29:18,582 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,582 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:29:18,583 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,600 INFO server Auth successful
2023-02-01 09:29:18,600 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,601 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:29:18,601 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,608 INFO server Auth successful
2023-02-01 09:29:18,608 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,609 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:29:18,609 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:29:18,714 INFO server Auth successful
2023-02-01 09:29:18,715 INFO server Imports value: import tensorflow as tf
2023-02-01 09:29:18,715 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:29:18,715 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:29:18] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,092 INFO server Auth successful
2023-02-01 09:30:29,092 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,092 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:30:29,092 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,114 INFO server Auth successful
2023-02-01 09:30:29,114 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,114 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:30:29,114 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,193 INFO server Auth successful
2023-02-01 09:30:29,194 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,194 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 09:30:29,194 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,265 INFO server Auth successful
2023-02-01 09:30:29,265 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,266 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:30:29,266 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,272 INFO server Auth successful
2023-02-01 09:30:29,272 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,272 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:30:29,272 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,366 INFO server Auth successful
2023-02-01 09:30:29,366 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,366 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:30:29,366 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,383 INFO server Auth successful
2023-02-01 09:30:29,383 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,383 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:30:29,384 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,414 INFO server Auth successful
2023-02-01 09:30:29,414 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,414 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:30:29,415 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 09:30:29,518 INFO server Auth successful
2023-02-01 09:30:29,518 INFO server Imports value: import tensorflow as tf
2023-02-01 09:30:29,519 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 09:30:29,519 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 09:30:29] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:01,272 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-01 15:07:01,272 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-01 15:07:55,758 INFO server Auth successful
2023-02-01 15:07:55,759 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:55,782 INFO server Auth successful
2023-02-01 15:07:55,782 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:55,834 INFO server Auth successful
2023-02-01 15:07:55,835 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:56,542 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-01 15:07:56,705 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 15:07:56,705 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 15:07:56,705 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 15:07:56,705 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 15:07:57,372 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 15:07:57,372 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,373 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 15:07:57,373 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,373 INFO server response-value: <Response 4 bytes [200 OK]>
2023-02-01 15:07:57,374 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,528 INFO server Auth successful
2023-02-01 15:07:57,528 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:57,575 INFO server Auth successful
2023-02-01 15:07:57,576 INFO server Auth successful
2023-02-01 15:07:57,594 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 15:07:57,594 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:57,594 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,594 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:57,595 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 15:07:57,596 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,596 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 15:07:57,597 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,698 INFO server Auth successful
2023-02-01 15:07:57,698 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:57,698 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 15:07:57,699 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,731 INFO server Auth successful
2023-02-01 15:07:57,731 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:57,732 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 15:07:57,732 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:07:57,753 INFO server Auth successful
2023-02-01 15:07:57,753 INFO server Imports value: import tensorflow as tf
2023-02-01 15:07:57,754 INFO server response-value: <Response 223 bytes [200 OK]>
2023-02-01 15:07:57,754 INFO werkzeug 129.173.67.60 - - [01/Feb/2023 15:07:57] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:10:30,390 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-02-01 15:10:30,390 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-01 15:10:39,840 INFO server Auth successful
2023-02-01 15:10:39,840 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:40,143 INFO server Auth successful
2023-02-01 15:10:40,143 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:40,144 INFO server Auth successful
2023-02-01 15:10:40,145 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:40,533 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-01 15:10:40,650 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 15:10:40,650 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 15:10:40,650 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 15:10:40,650 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 15:10:41,162 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,162 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,162 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,164 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,165 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,166 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,323 INFO server Auth successful
2023-02-01 15:10:41,323 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:41,371 INFO server Auth successful
2023-02-01 15:10:41,371 INFO server Auth successful
2023-02-01 15:10:41,388 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:41,388 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,389 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:41,389 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,390 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,390 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,390 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,391 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,491 INFO server Auth successful
2023-02-01 15:10:41,491 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:41,492 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,492 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,494 INFO server Auth successful
2023-02-01 15:10:41,495 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:41,495 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,495 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:41,527 INFO server Auth successful
2023-02-01 15:10:41,527 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:41,528 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:41,529 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:41] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:58,824 INFO server Auth successful
2023-02-01 15:10:58,824 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:58,824 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:58,825 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:58] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:58,865 INFO server Auth successful
2023-02-01 15:10:58,865 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:58,865 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:58,865 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:58] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:58,868 INFO server Auth successful
2023-02-01 15:10:58,868 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:58,868 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:58,869 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:58] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:58,997 INFO server Auth successful
2023-02-01 15:10:58,997 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:58,997 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:58,998 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:58] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:59,039 INFO server Auth successful
2023-02-01 15:10:59,039 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:59,040 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:59,040 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:59] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:59,052 INFO server Auth successful
2023-02-01 15:10:59,052 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:59,053 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:59,053 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:59] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:59,098 INFO server Auth successful
2023-02-01 15:10:59,098 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:59,098 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:59,099 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:59] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:59,160 INFO server Auth successful
2023-02-01 15:10:59,160 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:59,160 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:59,161 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:59] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:10:59,184 INFO server Auth successful
2023-02-01 15:10:59,184 INFO server Imports value: import tensorflow as tf
2023-02-01 15:10:59,185 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:10:59,185 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:10:59] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,465 INFO server Auth successful
2023-02-01 15:11:20,465 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,465 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,466 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,519 INFO server Auth successful
2023-02-01 15:11:20,519 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,520 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,520 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,571 INFO server Auth successful
2023-02-01 15:11:20,571 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,572 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,572 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,633 INFO server Auth successful
2023-02-01 15:11:20,633 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,634 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,634 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,694 INFO server Auth successful
2023-02-01 15:11:20,694 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,695 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,695 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,726 INFO server Auth successful
2023-02-01 15:11:20,726 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,727 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,727 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,747 INFO server Auth successful
2023-02-01 15:11:20,748 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,749 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,749 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,808 INFO server Auth successful
2023-02-01 15:11:20,809 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,809 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,810 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:11:20,867 INFO server Auth successful
2023-02-01 15:11:20,868 INFO server Imports value: import tensorflow as tf
2023-02-01 15:11:20,868 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 213, in run_function_and_return_result
    response = Response(
TypeError: __init__() got an unexpected keyword argument 'json'
2023-02-01 15:11:20,869 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:11:20] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-01 15:26:51,873 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-02-01 15:26:51,873 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-01 15:27:01,860 INFO server Auth successful
2023-02-01 15:27:01,861 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:01,946 INFO server Auth successful
2023-02-01 15:27:01,946 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:01,968 INFO server Auth successful
2023-02-01 15:27:01,969 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:02,633 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-01 15:27:02,794 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 15:27:02,794 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 15:27:02,794 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-01 15:27:02,794 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-01 15:27:03,457 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,458 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,458 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,458 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,459 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,460 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,626 INFO server Auth successful
2023-02-01 15:27:03,627 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:03,684 INFO server Auth successful
2023-02-01 15:27:03,684 INFO server Auth successful
2023-02-01 15:27:03,708 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:03,708 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:03,708 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,709 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,709 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,709 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,709 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,710 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,809 INFO server Auth successful
2023-02-01 15:27:03,809 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:03,810 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,810 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,823 INFO server Auth successful
2023-02-01 15:27:03,823 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:03,824 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,824 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:03,853 INFO server Auth successful
2023-02-01 15:27:03,853 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:03,854 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:03,854 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:03] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,101 INFO server Auth successful
2023-02-01 15:27:24,101 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,101 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,101 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,272 INFO server Auth successful
2023-02-01 15:27:24,273 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,273 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,274 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,282 INFO server Auth successful
2023-02-01 15:27:24,283 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,283 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,283 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,293 INFO server Auth successful
2023-02-01 15:27:24,293 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,293 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,294 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,392 INFO server Auth successful
2023-02-01 15:27:24,392 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,393 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,393 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,463 INFO server Auth successful
2023-02-01 15:27:24,463 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,464 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,464 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,484 INFO server Auth successful
2023-02-01 15:27:24,484 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,484 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,485 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,584 INFO server Auth successful
2023-02-01 15:27:24,584 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,585 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,585 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:24,606 INFO server Auth successful
2023-02-01 15:27:24,607 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:24,607 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:24,607 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:24] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,592 INFO server Auth successful
2023-02-01 15:27:38,592 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,592 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,593 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,613 INFO server Auth successful
2023-02-01 15:27:38,613 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,613 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,613 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,706 INFO server Auth successful
2023-02-01 15:27:38,706 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,706 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,707 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,761 INFO server Auth successful
2023-02-01 15:27:38,762 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,762 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,762 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,798 INFO server Auth successful
2023-02-01 15:27:38,798 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,799 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,799 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,868 INFO server Auth successful
2023-02-01 15:27:38,868 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,869 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,869 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,883 INFO server Auth successful
2023-02-01 15:27:38,883 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,884 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,884 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:38,911 INFO server Auth successful
2023-02-01 15:27:38,911 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:38,912 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:38,912 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:27:39,004 INFO server Auth successful
2023-02-01 15:27:39,004 INFO server Imports value: import tensorflow as tf
2023-02-01 15:27:39,005 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:27:39,005 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:27:39] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:32,832 INFO server Auth successful
2023-02-01 15:29:32,832 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:32,832 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:32,832 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:32] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:32,872 INFO server Auth successful
2023-02-01 15:29:32,872 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:32,872 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:32,872 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:32] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:32,989 INFO server Auth successful
2023-02-01 15:29:32,989 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:32,989 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:32,990 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:32] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:33,007 INFO server Auth successful
2023-02-01 15:29:33,007 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:33,008 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:33,008 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:33] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:33,040 INFO server Auth successful
2023-02-01 15:29:33,040 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:33,040 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:33,041 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:33] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:33,130 INFO server Auth successful
2023-02-01 15:29:33,131 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:33,132 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:33,132 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:33] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:33,155 INFO server Auth successful
2023-02-01 15:29:33,155 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:33,156 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:33,156 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:33] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:33,179 INFO server Auth successful
2023-02-01 15:29:33,180 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:33,180 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:33,181 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:33] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-01 15:29:33,300 INFO server Auth successful
2023-02-01 15:29:33,300 INFO server Imports value: import tensorflow as tf
2023-02-01 15:29:33,301 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-01 15:29:33,301 INFO werkzeug 127.0.0.1 - - [01/Feb/2023 15:29:33] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 11:08:47,423 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-02-02 11:08:47,423 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:09:56,988 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-02-02 11:09:56,988 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:24:38,009 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:12345
2023-02-02 11:24:38,010 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:26:23,747 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 11:26:23,747 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:26:34,702 INFO server Auth successful
2023-02-02 11:26:34,919 INFO server Imports value: import numpy as np
2023-02-02 11:26:34,949 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/tim/GreenAI-extension/server/server.py", line 213, in run_function_and_return_result
    results = run_function(
  File "/home/tim/GreenAI-extension/server/server.py", line 182, in run_function
    return_dict["method_object"] = obj
UnboundLocalError: local variable 'obj' referenced before assignment
2023-02-02 11:26:34,951 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 11:26:34] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 11:28:57,663 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:8080
 * Running on https://129.173.67.60:8080
2023-02-02 11:28:57,663 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:29:05,039 INFO server Auth successful
2023-02-02 11:29:05,281 INFO server Imports value: import numpy as np
2023-02-02 11:29:05,311 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/tim/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/tim/GreenAI-extension/server/server.py", line 213, in run_function_and_return_result
    results = run_function(
  File "/home/tim/GreenAI-extension/server/server.py", line 182, in run_function
    return_dict["method_object"] = obj
UnboundLocalError: local variable 'obj' referenced before assignment
2023-02-02 11:29:05,314 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 11:29:05] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 11:29:58,629 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:8080
 * Running on https://129.173.67.60:8080
2023-02-02 11:29:58,630 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:30:17,681 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:8080
 * Running on https://129.173.67.60:8080
2023-02-02 11:30:17,681 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 11:30:17,682 INFO werkzeug  * Restarting with stat
2023-02-02 11:30:18,080 WARNING werkzeug  * Debugger is active!
2023-02-02 11:30:18,080 INFO werkzeug  * Debugger PIN: 752-170-338
2023-02-02 11:30:22,590 INFO server Auth successful
2023-02-02 11:30:22,960 INFO server Imports value: import numpy as np
2023-02-02 11:30:22,998 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 11:30:22] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 12:10:56,631 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:8080
 * Running on https://129.173.67.60:8080
2023-02-02 12:10:56,631 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 12:10:56,632 INFO werkzeug  * Restarting with stat
2023-02-02 12:10:56,992 WARNING werkzeug  * Debugger is active!
2023-02-02 12:10:56,992 INFO werkzeug  * Debugger PIN: 752-170-338
2023-02-02 12:11:00,810 INFO server Auth successful
2023-02-02 12:11:01,042 INFO server Imports value: import numpy as np
2023-02-02 12:11:01,069 INFO server response-value: <Response 87263 bytes [200 OK]>
2023-02-02 12:11:01,070 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 12:11:01] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 12:11:20,938 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:8080
 * Running on https://129.173.67.60:8080
2023-02-02 12:11:20,938 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 12:11:20,938 INFO werkzeug  * Restarting with stat
2023-02-02 12:11:21,287 WARNING werkzeug  * Debugger is active!
2023-02-02 12:11:21,287 INFO werkzeug  * Debugger PIN: 752-170-338
2023-02-02 12:15:14,016 INFO server Auth successful
2023-02-02 12:15:14,235 INFO server Imports value: import numpy as np
2023-02-02 12:15:14,268 INFO server response-value: <Response 115391 bytes [200 OK]>
2023-02-02 12:15:14,269 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 12:15:14] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 12:16:22,835 INFO server Auth successful
2023-02-02 12:16:23,080 INFO server Imports value: import numpy as np
2023-02-02 12:16:23,109 INFO server response-value: <Response 125963 bytes [200 OK]>
2023-02-02 12:16:23,110 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 12:16:23] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 12:19:19,743 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:8080
 * Running on https://129.173.67.60:8080
2023-02-02 12:19:19,743 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 12:19:19,744 INFO werkzeug  * Restarting with stat
2023-02-02 12:19:20,098 WARNING werkzeug  * Debugger is active!
2023-02-02 12:19:20,099 INFO werkzeug  * Debugger PIN: 752-170-338
2023-02-02 12:19:22,387 INFO server Auth successful
2023-02-02 12:19:22,700 INFO server Imports value: import numpy as np
2023-02-02 12:19:22,737 INFO server response-value: <Response 131529 bytes [200 OK]>
2023-02-02 12:19:22,739 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 12:19:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 12:21:12,926 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 12:21:12,926 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 12:21:12,927 INFO werkzeug  * Restarting with stat
2023-02-02 12:21:13,309 WARNING werkzeug  * Debugger is active!
2023-02-02 12:21:13,309 INFO werkzeug  * Debugger PIN: 752-170-338
2023-02-02 12:21:22,521 INFO server Auth successful
2023-02-02 12:21:23,154 INFO server Imports value: import numpy as np
2023-02-02 12:21:23,191 INFO server response-value: <Response 131529 bytes [200 OK]>
2023-02-02 12:21:23,192 INFO werkzeug 81.129.217.195 - - [02/Feb/2023 12:21:23] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:27:47,198 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 19:27:47,199 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 19:28:25,184 INFO server Auth successful
2023-02-02 19:28:25,184 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:25,208 INFO server Auth successful
2023-02-02 19:28:25,210 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:25,256 INFO server Auth successful
2023-02-02 19:28:25,258 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:25,961 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-02 19:28:26,076 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 19:28:26,076 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 19:28:26,076 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 19:28:26,076 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 19:28:26,663 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:28:26,665 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:28:26,670 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:28:26,677 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:28:26,692 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:28:26,692 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:28:26,864 INFO server Auth successful
2023-02-02 19:28:26,864 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:26,916 INFO server Auth successful
2023-02-02 19:28:26,917 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:26,938 INFO server Auth successful
2023-02-02 19:28:26,939 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:26,941 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:26,941 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:26,941 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:26,943 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:26] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:26,943 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:26] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:26,943 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:26] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:27,051 INFO server Auth successful
2023-02-02 19:28:27,052 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:27,052 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:27,053 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:27] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:27,053 INFO server Auth successful
2023-02-02 19:28:27,053 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:27,054 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:27,054 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:27] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:27,064 INFO server Auth successful
2023-02-02 19:28:27,064 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:27,065 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:27,065 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:27] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,040 INFO server Auth successful
2023-02-02 19:28:51,040 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,041 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,041 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,064 INFO server Auth successful
2023-02-02 19:28:51,064 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,064 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,065 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,095 INFO server Auth successful
2023-02-02 19:28:51,096 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,096 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,097 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,244 INFO server Auth successful
2023-02-02 19:28:51,245 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,246 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,246 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,251 INFO server Auth successful
2023-02-02 19:28:51,251 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,252 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,252 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,292 INFO server Auth successful
2023-02-02 19:28:51,292 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,293 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,293 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,363 INFO server Auth successful
2023-02-02 19:28:51,363 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,364 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,364 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,381 INFO server Auth successful
2023-02-02 19:28:51,381 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,382 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,382 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:28:51,410 INFO server Auth successful
2023-02-02 19:28:51,411 INFO server Imports value: import tensorflow as tf
2023-02-02 19:28:51,412 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:28:51,412 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:28:51] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,504 INFO server Auth successful
2023-02-02 19:31:17,504 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,504 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,505 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,528 INFO server Auth successful
2023-02-02 19:31:17,528 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,529 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,529 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,550 INFO server Auth successful
2023-02-02 19:31:17,550 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,551 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,551 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,684 INFO server Auth successful
2023-02-02 19:31:17,685 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,685 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,686 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,687 INFO server Auth successful
2023-02-02 19:31:17,687 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,687 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,687 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,715 INFO server Auth successful
2023-02-02 19:31:17,715 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,715 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,715 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,789 INFO server Auth successful
2023-02-02 19:31:17,789 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,789 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,790 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,823 INFO server Auth successful
2023-02-02 19:31:17,824 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,824 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,825 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:17,840 INFO server Auth successful
2023-02-02 19:31:17,841 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:17,841 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:17,842 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:17] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:49,994 INFO server Auth successful
2023-02-02 19:31:49,994 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:49,995 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:49,995 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:49] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,024 INFO server Auth successful
2023-02-02 19:31:50,024 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,025 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,025 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,073 INFO server Auth successful
2023-02-02 19:31:50,074 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,074 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,074 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,161 INFO server Auth successful
2023-02-02 19:31:50,162 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,162 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,162 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,192 INFO server Auth successful
2023-02-02 19:31:50,192 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,192 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,193 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,247 INFO server Auth successful
2023-02-02 19:31:50,247 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,247 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,248 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,261 INFO server Auth successful
2023-02-02 19:31:50,261 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,261 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,262 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,301 INFO server Auth successful
2023-02-02 19:31:50,301 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,302 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,302 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:50,415 INFO server Auth successful
2023-02-02 19:31:50,415 INFO server Imports value: import tensorflow as tf
2023-02-02 19:31:50,416 ERROR server Exception on /api/run_experiment [POST]
Traceback (most recent call last):
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/saurabh/code-energy-consumption/server/server.py", line 209, in run_function_and_return_result
    results = run_function(
  File "/home/saurabh/code-energy-consumption/server/server.py", line 161, in run_function
    df_cpu, df_ram = parse_perf(PERF_FILE)
  File "/home/saurabh/code-energy-consumption/server/measurement_parse.py", line 31, in parse_perf
    # start_datetime = datetime.strptime(start_datetime_str, '%c')
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu Feb  2 12:11:20 2023' does not match format '%c'
2023-02-02 19:31:50,416 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:31:50] "[35m[1mPOST /api/run_experiment HTTP/1.1[0m" 500 -
2023-02-02 19:31:57,904 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 19:31:57,904 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 19:32:04,668 INFO server Auth successful
2023-02-02 19:32:04,669 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:04,765 INFO server Auth successful
2023-02-02 19:32:04,766 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:04,958 INFO server Auth successful
2023-02-02 19:32:04,958 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:05,436 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-02 19:32:05,549 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 19:32:05,550 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 19:32:05,550 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 19:32:05,550 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 19:32:06,156 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,159 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,206 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,207 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,217 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,218 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,390 INFO server Auth successful
2023-02-02 19:32:06,390 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:06,447 INFO server Auth successful
2023-02-02 19:32:06,448 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:06,448 INFO server Auth successful
2023-02-02 19:32:06,477 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:06,513 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,514 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,516 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,516 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,517 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,517 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,621 INFO server Auth successful
2023-02-02 19:32:06,622 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:06,632 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,633 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,633 INFO server Auth successful
2023-02-02 19:32:06,633 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:06,643 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,644 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:32:06,644 INFO server Auth successful
2023-02-02 19:32:06,645 INFO server Imports value: import tensorflow as tf
2023-02-02 19:32:06,655 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:32:06,655 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:32:06] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,036 INFO server Auth successful
2023-02-02 19:33:22,036 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,045 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,045 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,117 INFO server Auth successful
2023-02-02 19:33:22,117 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,127 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,127 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,161 INFO server Auth successful
2023-02-02 19:33:22,162 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,170 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,170 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,217 INFO server Auth successful
2023-02-02 19:33:22,217 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,227 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,227 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,313 INFO server Auth successful
2023-02-02 19:33:22,313 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,322 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,322 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,324 INFO server Auth successful
2023-02-02 19:33:22,325 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,332 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,332 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,345 INFO server Auth successful
2023-02-02 19:33:22,346 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,355 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,355 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,425 INFO server Auth successful
2023-02-02 19:33:22,425 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,435 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,435 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:22,462 INFO server Auth successful
2023-02-02 19:33:22,462 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:22,471 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:22,471 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:22] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:29,285 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 19:33:29,285 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 19:33:36,329 INFO server Auth successful
2023-02-02 19:33:36,330 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:36,398 INFO server Auth successful
2023-02-02 19:33:36,399 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:36,420 INFO server Auth successful
2023-02-02 19:33:36,424 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:37,097 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-02 19:33:37,212 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 19:33:37,212 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 19:33:37,212 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 19:33:37,212 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 19:33:37,840 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:37,841 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:37] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:37,886 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:37,887 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:37] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:37,891 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:37,891 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:37] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:38,051 INFO server Auth successful
2023-02-02 19:33:38,051 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:38,100 INFO server Auth successful
2023-02-02 19:33:38,100 INFO server Auth successful
2023-02-02 19:33:38,117 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:38,121 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:38,134 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:38,135 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:38,142 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:38,142 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:38,143 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:38,143 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:38,259 INFO server Auth successful
2023-02-02 19:33:38,260 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:38,269 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:38,270 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:38,280 INFO server Auth successful
2023-02-02 19:33:38,280 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:38,290 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:38,290 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:33:38,303 INFO server Auth successful
2023-02-02 19:33:38,303 INFO server Imports value: import tensorflow as tf
2023-02-02 19:33:38,312 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:33:38,313 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:33:38] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,512 INFO server Auth successful
2023-02-02 19:36:30,512 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,523 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,523 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,584 INFO server Auth successful
2023-02-02 19:36:30,584 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,593 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,593 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,612 INFO server Auth successful
2023-02-02 19:36:30,612 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,622 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,622 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,703 INFO server Auth successful
2023-02-02 19:36:30,704 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,711 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,712 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,773 INFO server Auth successful
2023-02-02 19:36:30,773 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,781 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,781 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,788 INFO server Auth successful
2023-02-02 19:36:30,788 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,796 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,796 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,821 INFO server Auth successful
2023-02-02 19:36:30,821 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,828 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,829 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,904 INFO server Auth successful
2023-02-02 19:36:30,904 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,911 INFO server Auth successful
2023-02-02 19:36:30,911 INFO server Imports value: import tensorflow as tf
2023-02-02 19:36:30,915 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,918 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:36:30,922 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:36:30,922 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:36:30] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,144 INFO server Auth successful
2023-02-02 19:37:26,144 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,153 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,154 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,167 INFO server Auth successful
2023-02-02 19:37:26,167 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,176 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,176 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,203 INFO server Auth successful
2023-02-02 19:37:26,203 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,212 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,212 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,323 INFO server Auth successful
2023-02-02 19:37:26,324 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,332 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,333 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,336 INFO server Auth successful
2023-02-02 19:37:26,336 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,343 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,343 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,380 INFO server Auth successful
2023-02-02 19:37:26,380 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,388 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,389 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,430 INFO server Auth successful
2023-02-02 19:37:26,430 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,437 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,437 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,458 INFO server Auth successful
2023-02-02 19:37:26,459 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,471 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,471 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:37:26,503 INFO server Auth successful
2023-02-02 19:37:26,504 INFO server Imports value: import tensorflow as tf
2023-02-02 19:37:26,513 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 19:37:26,513 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 19:37:26] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 19:40:31,089 INFO werkzeug 164.90.168.253 - - [02/Feb/2023 19:40:31] "[33mGET /ab2g HTTP/1.1[0m" 404 -
2023-02-02 19:40:31,537 INFO werkzeug 164.90.168.253 - - [02/Feb/2023 19:40:31] "[33mGET /ab2h HTTP/1.1[0m" 404 -
2023-02-02 19:40:32,196 INFO werkzeug 164.90.168.253 - - [02/Feb/2023 19:40:32] "GET / HTTP/1.1" 200 -
2023-02-02 20:41:01,170 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 20:41:01,170 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 20:59:37,452 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 20:59:37,452 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 20:59:47,820 INFO server Auth successful
2023-02-02 20:59:47,820 INFO server Imports value: import tensorflow as tf
2023-02-02 20:59:48,684 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-02 20:59:48,792 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 20:59:48,792 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 20:59:48,792 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 20:59:48,792 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 20:59:49,348 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 20:59:49,348 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 20:59:49] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 20:59:49,449 INFO server Auth successful
2023-02-02 20:59:49,449 INFO server Imports value: import tensorflow as tf
2023-02-02 20:59:49,457 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 20:59:49,457 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 20:59:49] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 20:59:49,557 INFO server Auth successful
2023-02-02 20:59:49,557 INFO server Imports value: import tensorflow as tf
2023-02-02 20:59:49,565 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 20:59:49,566 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 20:59:49] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:23:05,086 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 21:23:05,086 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 21:23:11,993 INFO server Auth successful
2023-02-02 21:23:11,993 INFO server Imports value: import tensorflow as tf
2023-02-02 21:23:12,794 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-02 21:23:12,906 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 21:23:12,906 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 21:23:12,906 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 21:23:12,906 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 21:23:13,430 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:23:13,430 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:23:13] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:23:13,540 INFO server Auth successful
2023-02-02 21:23:13,541 INFO server Imports value: import tensorflow as tf
2023-02-02 21:23:13,549 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:23:13,549 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:23:13] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:23:13,664 INFO server Auth successful
2023-02-02 21:23:13,664 INFO server Imports value: import tensorflow as tf
2023-02-02 21:23:13,672 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:23:13,673 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:23:13] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:24:41,944 INFO server Auth successful
2023-02-02 21:24:41,945 INFO server Imports value: import tensorflow as tf
2023-02-02 21:24:41,954 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:24:41,954 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:24:41] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:24:42,061 INFO server Auth successful
2023-02-02 21:24:42,061 INFO server Imports value: import tensorflow as tf
2023-02-02 21:24:42,070 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:24:42,071 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:24:42] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:24:42,177 INFO server Auth successful
2023-02-02 21:24:42,177 INFO server Imports value: import tensorflow as tf
2023-02-02 21:24:42,187 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:24:42,187 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:24:42] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:29:02,162 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://129.173.67.60:8080
2023-02-02 21:29:02,162 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-02-02 21:29:07,962 INFO server Auth successful
2023-02-02 21:29:07,962 INFO server Imports value: import tensorflow as tf
2023-02-02 21:29:08,704 DEBUG tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-02-02 21:29:08,865 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 21:29:08,865 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 21:29:08,865 DEBUG h5py._conv Creating converter from 7 to 5
2023-02-02 21:29:08,865 DEBUG h5py._conv Creating converter from 5 to 7
2023-02-02 21:29:09,409 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:29:09,410 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:29:09] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:29:09,524 INFO server Auth successful
2023-02-02 21:29:09,525 INFO server Imports value: import tensorflow as tf
2023-02-02 21:29:09,532 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:29:09,533 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:29:09] "POST /api/run_experiment HTTP/1.1" 200 -
2023-02-02 21:29:09,649 INFO server Auth successful
2023-02-02 21:29:09,649 INFO server Imports value: import tensorflow as tf
2023-02-02 21:29:09,657 INFO server response-value: <Response likely-streamed [200 OK]>
2023-02-02 21:29:09,657 INFO werkzeug 129.173.67.60 - - [02/Feb/2023 21:29:09] "POST /api/run_experiment HTTP/1.1" 200 -
